<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework Generator
 *
 * **********************************************************************************************
 *
 * This is file is autogenerated
 *
 ************************************************************************************************/

/**
 *
 */
abstract class AutoBlogEntryTag extends IdentifiableOrmEntity implements IOrmRelated, IDaoRelated
{
	/**
	 * @var scalar
	 */
	protected $id;

	/**
	 * @var scalar
	 */
	protected $name;

	/**
	 * @var scalar
	 */
	protected $restId;

	/**
	 * @return BlogEntryTagEntity
	 */
	static function orm()
	{
		return BlogEntryTagEntity::getInstance();
	}

	/**
	 * @return IOrmEntityMapper
	 */
	static function map()
	{
		return self::orm()->getMap();
	}

	/**
	 * @return IOrmEntityAccessor
	 */
	static function dao()
	{
		return self::orm()->getDao();
	}

	/**
	 * @return EntityQuery
	 */
	static function query()
	{
		return new EntityQuery(self::orm());
	}

	/**
	 * @param scalar $id
	 * @return BlogEntryTag itself
	 */
	function setId($id)
	{
		$this->id = $id;

		return $this;
	}

	function _setId($id)
	{
		$this->setId($id);

		return $this;
	}

	/**
	 * @return mixed
	 */
	function getId()
	{
		return $this->id;
	}

	function _getId()
	{
		return $this->getId();
	}

	/**
	 * @param scalar $name
	 * @return BlogEntryTag itself
	 */
	function setName($name)
	{
		$this->name = $name;

		return $this;
	}

	/**
	 * @return mixed
	 */
	function getName()
	{
		return $this->name;
	}

	/**
	 * @param scalar $restId
	 * @return BlogEntryTag itself
	 */
	function setRestId($restId)
	{
		$this->restId = $restId;

		return $this;
	}

	/**
	 * @return mixed
	 */
	function getRestId()
	{
		return $this->restId;
	}
}

?>