<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework Generator
 *
 * **********************************************************************************************
 *
 * This is file is autogenerated
 *
 ************************************************************************************************/

/**
 *
 */
abstract class AutoBlogEntry extends IdentifiableOrmEntity implements IOrmRelated, IDaoRelated
{
	/**
	 * @var scalar
	 */
	protected $id;

	/**
	 * @var scalar
	 */
	protected $title;

	/**
	 * @var scalar
	 */
	protected $text;

	/**
	 * @var Timestamp
	 */
	protected $pubTime;

	/**
	 * @var Date
	 */
	protected $pubDate;

	/**
	 * @var scalar
	 */
	protected $restId;

	/**
	 * @return BlogEntryEntity
	 */
	static function orm()
	{
		return BlogEntryEntity::getInstance();
	}

	/**
	 * @return IOrmEntityMapper
	 */
	static function map()
	{
		return self::orm()->getMap();
	}

	/**
	 * @return IOrmEntityAccessor
	 */
	static function dao()
	{
		return self::orm()->getDao();
	}

	/**
	 * @return EntityQuery
	 */
	static function query()
	{
		return new EntityQuery(self::orm());
	}

	/**
	 * @param scalar $id
	 * @return BlogEntry itself
	 */
	function setId($id)
	{
		$this->id = $id;

		return $this;
	}

	function _setId($id)
	{
		$this->setId($id);

		return $this;
	}

	/**
	 * @return mixed
	 */
	function getId()
	{
		return $this->id;
	}

	function _getId()
	{
		return $this->getId();
	}

	/**
	 * @param scalar $title
	 * @return BlogEntry itself
	 */
	function setTitle($title)
	{
		$this->title = $title;

		return $this;
	}

	/**
	 * @return mixed
	 */
	function getTitle()
	{
		return $this->title;
	}

	/**
	 * @param scalar $text
	 * @return BlogEntry itself
	 */
	function setText($text)
	{
		$this->text = $text;

		return $this;
	}

	/**
	 * @return mixed
	 */
	function getText()
	{
		return $this->text;
	}

	/**
	 * @param Timestamp $pubTime
	 * @return BlogEntry itself
	 */
	function setPubTime(Timestamp $pubTime)
	{
		$this->pubTime = $pubTime;

		return $this;
	}

	/**
	 * @return Timestamp
	 */
	function getPubTime()
	{
		return $this->pubTime;
	}

	/**
	 * @param Date $pubDate
	 * @return BlogEntry itself
	 */
	function setPubDate(Date $pubDate)
	{
		$this->pubDate = $pubDate;

		return $this;
	}

	/**
	 * @return Date
	 */
	function getPubDate()
	{
		return $this->pubDate;
	}

	/**
	 * @param scalar $restId
	 * @return BlogEntry itself
	 */
	function setRestId($restId)
	{
		$this->restId = $restId;

		return $this;
	}

	/**
	 * @return mixed
	 */
	function getRestId()
	{
		return $this->restId;
	}
}

?>