<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework v.1.0.0
 *
 * **********************************************************************************************
 *
 * This is an auxiliary autogenerated file. Do not edit it as it can be regenerated implicitly!
 *
 ************************************************************************************************/

/**
 * Autogenerated class
 */
abstract class AutoBlogEntryEntity extends LazySingleton implements IQueryable
{
	/**
	 * @return IOrmEntityMapper
	 */
	function getMap()
	{
		return new OrmMap($this->getLogicalSchema());
	}

	/**
	 * @return ILogicallySchematic
	 */
	function getLogicalSchema()
	{
		return new BlogEntryEntityLogicalSchema;
	}

	/**
	 * @return IOrmEntityAccessor
	 */
	function getDao()
	{
		return new RdbmsDao(
			DBPool::getDefault(),
			$this
		);
	}

	/**
	 * @return IPhysicallySchematic
	 */
	function getPhysicalSchema()
	{
		return new BlogEntryEntityPhysicalSchema;
	}
}

?>