<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework Generator
 *
 * **********************************************************************************************
 *
 * This is file is autogenerated
 *
 ************************************************************************************************/

/**
 *
 */
abstract class AutoBlogEntryBlogTag extends OrmEntity implements IOrmRelated, IDaoRelated
{
	/**
	 * @var BlogEntry
	 */
	protected $BlogEntry;

	/**
	 * @var BlogEntryTag
	 */
	protected $BlogEntryTag;

	/**
	 * @return BlogEntryBlogTagEntity
	 */
	static function orm()
	{
		return BlogEntryBlogTagEntity::getInstance();
	}

	/**
	 * @return IOrmEntityMapper
	 */
	static function map()
	{
		return self::orm()->getMap();
	}

	/**
	 * @return IOrmEntityAccessor
	 */
	static function dao()
	{
		return self::orm()->getDao();
	}

	/**
	 * @return EntityQuery
	 */
	static function query()
	{
		return new EntityQuery(self::orm());
	}

	/**
	 * @param BlogEntry $BlogEntry
	 * @return BlogEntryBlogTag itself
	 */
	function setBlogEntry(BlogEntry $BlogEntry)
	{
		$this->BlogEntry = $BlogEntry;

		return $this;
	}

	/**
	 * @return BlogEntry
	 */
	function getBlogEntry()
	{
//		if ($this->BlogEntry) { // thats is what called lazy fetching
//			$this->BlogEntry->fetch();
//		}

		return $this->BlogEntry;
	}

	/**
	 * @param BlogEntryTag $BlogEntryTag
	 * @return BlogEntryBlogTag itself
	 */
	function setBlogEntryTag(BlogEntryTag $BlogEntryTag)
	{
		$this->BlogEntryTag = $BlogEntryTag;

		return $this;
	}

	/**
	 * @return BlogEntryTag
	 */
	function getBlogEntryTag()
	{
//		if ($this->BlogEntryTag) { // thats is what called lazy fetching
//			$this->BlogEntryTag->fetch();
//		}

		return $this->BlogEntryTag;
	}
}

?>