<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework v.1.2.0 Copyright (c) 2010 Scand Ltd.
 *
 * **********************************************************************************************
 *
 * Generated at 2010/05/09 17:23
 *
 * This is an auxiliary autogenerated file. Do not edit it as it can be regenerated implicitly!
 *
 ************************************************************************************************/

/**
 * Autogenerated class
 */
abstract class AutoAnnouncement extends IdentifiableOrmEntity implements IOrmRelated, IDaoRelated
{
	/**
	 * @var scalar|null
	 */
	protected $id;

	/**
	 * @var scalar
	 */
	protected $text;

	/**
	 * @var Date
	 */
	protected $date;

	/**
	 * @return AnnouncementEntity
	 */
	static function orm()
	{
		return AnnouncementEntity::getInstance();
	}

	/**
	 * @return IOrmEntityMapper
	 */
	static function map()
	{
		return self::orm()->getMap();
	}

	/**
	 * @return IOrmEntityAccessor
	 */
	static function dao()
	{
		return self::orm()->getDao();
	}

	/**
	 * @return EntityQuery
	 */
	static function query()
	{
		return new EntityQuery(self::orm());
	}

	/**
	 * @param scalar $id
	 * @return Announcement itself
	 */
	function setId($id = null)
	{
		$this->id = $id;

		return $this;
	}

	function _setId($id)
	{
		$this->setId($id);

		return $this;
	}

	/**
	 * @return mixed|null
	 */
	function getId()
	{
		return $this->id;
	}

	function _getId()
	{
		return $this->getId();
	}

	/**
	 * @param scalar $text
	 * @return Announcement itself
	 */
	function setText($text)
	{
		$this->text = $text;

		return $this;
	}

	/**
	 * @return mixed
	 */
	function getText()
	{
		return $this->text;
	}

	/**
	 * @param Date $date
	 * @return Announcement itself
	 */
	function setDate(Date $date)
	{
		$this->date = $date;

		return $this;
	}

	/**
	 * @return Date
	 */
	function getDate()
	{
		return $this->date;
	}
}

?>