<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework Generator
 *
 * **********************************************************************************************
 *
 * This is file is autogenerated
 *
 ************************************************************************************************/

/**
 *
 */
abstract class AutoConfigurationEntry extends IdentifiableOrmEntity implements IOrmRelated, IDaoRelated
{
	/**
	 * @var ConfigurationKey
	 */
	private $id;

	/**
	 * @var string
	 */
	private $value;

	/**
	 * @return ConfigurationEntryEntity
	 */
	static function orm()
	{
		return ConfigurationEntryEntity::getInstance();
	}

	/**
	 * @return IOrmEntityMapper
	 */
	static function map()
	{
		return self::orm()->getMap();
	}

	/**
	 * @return IOrmEntityAccessor
	 */
	static function dao()
	{
		return self::orm()->getDao();
	}

	/**
	 * @param ConfigurationKey id
	 * @throws ArgumentException
	 * @return ConfigurationEntry an object itself
	 */
	function setId(ConfigurationKey $id = null)
	{
		$this->id = $id;

		return $this;
	}

	/**
	 * @internal
	 * @return ConfigurationEntry an object itself
	 */
	function _setId($id)
	{
		$this->setId($id);

		return $this;
	}

	/**
	 * @return ConfigurationKey|null
	 */
	function getId()
	{
		return $this->id;
	}

	/**
	 * @internal
	 * @return ConfigurationKey|null
	 */
	function _getId()
	{
		return $this->getId();
	}

	/**
	 * @param string value
	 * @throws ArgumentException
	 * @return ConfigurationEntry an object itself
	 */
	function setValue(/* String */ $value)
	{
		$this->value = String::cast($value)->getValue();

		return $this;
	}

	/**
	 * @return string
	 */
	function getValue()
	{
		return $this->value;
	}
}

?>