<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework Generator
 *
 * **********************************************************************************************
 *
 * This is file is autogenerated
 *
 ************************************************************************************************/

/**
 *
 */
abstract class AutoBlogEntryTag extends IdentifiableOrmEntity implements IOrmRelated, IDaoRelated
{
	/**
	 * @var integer
	 */
	private $id;

	/**
	 * @var string
	 */
	private $name;

	/**
	 * @var string
	 */
	private $restId;

	/**
	 * @return BlogEntryTagEntity
	 */
	static function orm()
	{
		return BlogEntryTagEntity::getInstance();
	}

	/**
	 * @return IOrmEntityMapper
	 */
	static function map()
	{
		return self::orm()->getMap();
	}

	/**
	 * @return IOrmEntityAccessor
	 */
	static function dao()
	{
		return self::orm()->getDao();
	}

	/**
	 * @param integer id
	 * @throws ArgumentException
	 * @return BlogEntryTag an object itself
	 */
	function setId(/* Integer */ $id = null)
	{
		$this->id = is_null($id) ? null : Integer::cast($id)->getValue();

		return $this;
	}

	/**
	 * @internal
	 * @return BlogEntryTag an object itself
	 */
	function _setId($id)
	{
		$this->setId($id);

		return $this;
	}

	/**
	 * @return integer|null
	 */
	function getId()
	{
		return $this->id;
	}

	/**
	 * @internal
	 * @return integer|null
	 */
	function _getId()
	{
		return $this->getId();
	}

	/**
	 * @param string name
	 * @throws ArgumentException
	 * @return BlogEntryTag an object itself
	 */
	function setName(/* String */ $name)
	{
		$this->name = String::cast($name)->getValue();

		return $this;
	}

	/**
	 * @return string
	 */
	function getName()
	{
		return $this->name;
	}

	/**
	 * @param string restId
	 * @throws ArgumentException
	 * @return BlogEntryTag an object itself
	 */
	function setRestId(/* String */ $restId)
	{
		$this->restId = String::cast($restId)->getValue();

		return $this;
	}

	/**
	 * @return string
	 */
	function getRestId()
	{
		return $this->restId;
	}
}

?>