<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework Generator
 *
 * **********************************************************************************************
 *
 * This is file is autogenerated
 *
 ************************************************************************************************/

/**
 *
 */
abstract class AutoConfigurationEntry extends IdentifiableOrmEntity implements IOrmRelated, IDaoRelated
{
	/**
	 * @var ConfigurationKey
	 */
	protected $id;

	/**
	 * @var scalar
	 */
	protected $value;

	/**
	 * @return ConfigurationEntryEntity
	 */
	static function orm()
	{
		return ConfigurationEntryEntity::getInstance();
	}

	/**
	 * @return IOrmEntityMapper
	 */
	static function map()
	{
		return self::orm()->getMap();
	}

	/**
	 * @return IOrmEntityAccessor
	 */
	static function dao()
	{
		return self::orm()->getDao();
	}

	/**
	 * @return EntityQuery
	 */
	static function query()
	{
		return new EntityQuery(self::orm());
	}

	/**
	 * @param ConfigurationKey $id
	 * @return ConfigurationEntry itself
	 */
	function setId(ConfigurationKey $id)
	{
		$this->id = $id;

		return $this;
	}

	function _setId($id)
	{
		$this->setId($id);

		return $this;
	}

	/**
	 * @return ConfigurationKey
	 */
	function getId()
	{
		return $this->id;
	}

	function _getId()
	{
		return $this->getId();
	}

	/**
	 * @param scalar $value
	 * @return ConfigurationEntry itself
	 */
	function setValue($value)
	{
		$this->value = $value;

		return $this;
	}

	/**
	 * @return mixed
	 */
	function getValue()
	{
		return $this->value;
	}
}

?>