<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework Generator
 *
 * **********************************************************************************************
 *
 * This is file is autogenerated
 *
 ************************************************************************************************/

/**
 *
 */
final class BlogEntryTagEntityLogicalSchema implements ILogicallySchematic
{
	private $propertyNames = array('id', 'name', 'restId', 'blogEntries');

	/**
	 * Returns the name of the class representing an entity
	 * @return string
	 */
	function getEntityName()
	{
		return 'BlogEntryTag';
	}

	/**
	 * @return OrmEntity
	 */
	function getNewEntity()
	{
		return new BlogEntryTag;
	}

	/**
	 * @return OrmProperty|null
	 */
	function getIdentifier()
	{
		return new OrmProperty('id', array('id'), new FundamentalPropertyType(new DBType(DBType::UINT32, false, null, null, null, true)), new OrmPropertyVisibility(OrmPropertyVisibility::FULL), false, true);
	}

	/**
	 * Gets the set of {@link OrmProperty}
	 * @return array
	 */
	function getProperties()
	{
		return array(
			'id' => $this->getIdentifier(),
			'name' => new OrmProperty('name', array('name'), new FundamentalPropertyType(new DBType(DBType::VARCHAR, false, null, null, null, false)), new OrmPropertyVisibility(OrmPropertyVisibility::FULL), false, false),
			'restId' => new OrmProperty('restId', array('rest_id'), new FundamentalPropertyType(new DBType(DBType::VARCHAR, false, null, null, null, false)), new OrmPropertyVisibility(OrmPropertyVisibility::FULL), true, false),
			'blogEntries' => new OrmProperty('blogEntries', array(), new ManyToManyContainerPropertyType(BlogEntryBlogTag::orm(), BlogEntryBlogTag::orm()->getLogicalSchema()->getProperty('BlogEntryTag'), BlogEntryBlogTag::orm()->getLogicalSchema()->getProperty('BlogEntry')), new OrmPropertyVisibility(OrmPropertyVisibility::TRANSPARENT), false, false)
		);
	}

	/**
	 * @return OrmProperty
	 */
	function getProperty($name)
	{
		if (!in_array($name, $this->propertyNames)) {
			throw new ArgumentException('name', $name);
		}

		$properties = $this->getProperties();

		return $properties[$name];
	}
}

?>