<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework Generator
 *
 * **********************************************************************************************
 *
 * This is file is autogenerated
 *
 ************************************************************************************************/

/**
 *
 */
final class BlogEntryEntityLogicalSchema implements ILogicallySchematic
{
	private $propertyNames = array('id','title','text','pubTime','pubDate','restId','entryTags');

	/**
	 * Returns the name of the class representing an entity
	 * @return string
	 */
	function getEntityName()
	{
		return 'BlogEntry';
	}

	/**
	 * @return OrmEntity
	 */
	function getNewEntity()
	{
		return new BlogEntry;
	}

	/**
	 * @return IOrmProperty|null
	 */
	function getIdentifier()
	{
		return new OrmProperty('id',array('id'),new AutoIntPropertyType(true),new OrmPropertyVisibility(OrmPropertyVisibility::FULL),false);
	}

	/**
	 * Gets the set of {@link IOrmProperty}
	 * @return array
	 */
	function getProperties()
	{
		return array(
			'id' => new OrmProperty('id',array('id'),new AutoIntPropertyType(true),new OrmPropertyVisibility(OrmPropertyVisibility::FULL),false),
			'title' => new OrmProperty('title',array('title'),new VarcharPropertyType(null,null,false),new OrmPropertyVisibility(OrmPropertyVisibility::FULL),false),
			'text' => new OrmProperty('text',array('text'),new VarcharPropertyType(null,null,false),new OrmPropertyVisibility(OrmPropertyVisibility::FULL),false),
			'pubTime' => new OrmProperty('pubTime',array('pub_time'),new TimestampPropertyType(false),new OrmPropertyVisibility(OrmPropertyVisibility::FULL),false),
			'pubDate' => new OrmProperty('pubDate',array('pub_date'),new DatePropertyType(false),new OrmPropertyVisibility(OrmPropertyVisibility::FULL),false),
			'restId' => new OrmProperty('restId',array('rest_id'),new VarcharPropertyType(null,null,false),new OrmPropertyVisibility(OrmPropertyVisibility::FULL),false),
			'entryTags' => new OrmProperty('entryTags',array(),new ManyToManyContainerPropertyType(BlogEntryBlogTag::orm(),BlogEntryBlogTag::orm()->getLogicalSchema()->getProperty('BlogEntry'),BlogEntryBlogTag::orm()->getLogicalSchema()->getProperty('BlogEntryTag')),new OrmPropertyVisibility(OrmPropertyVisibility::TRANSPARENT),false)
		);
	}

	/**
	 * @return IOrmProperty
	 */
	function getProperty($name)
	{
		if (!in_array($name, $this->propertyNames)) {
			throw new ArgumentException('name', $name);
		}

		$properties = $this->getProperties();

		return $properties[$name];
	}
}

?>