<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework Generator
 *
 * **********************************************************************************************
 *
 * This is file is autogenerated
 *
 ************************************************************************************************/

/**
 *
 */
final class BlogEntryTagEntityLogicalSchema implements ILogicallySchematic
{
	private $propertyNames = array('id','name','restId','blogEntries');

	/**
	 * Returns the name of the class representing an entity
	 * @return string
	 */
	function getEntityName()
	{
		return 'BlogEntryTag';
	}

	/**
	 * @return OrmEntity
	 */
	function getNewEntity()
	{
		return new BlogEntryTag;
	}

	/**
	 * @return IOrmProperty|null
	 */
	function getIdentifier()
	{
		return new OrmProperty('id',array('id'),new AutoIntPropertyType(true),new OrmPropertyVisibility(OrmPropertyVisibility::FULL),false);
	}

	/**
	 * Gets the set of {@link IOrmProperty}
	 * @return array
	 */
	function getProperties()
	{
		return array(
			'id' => new OrmProperty('id',array('id'),new AutoIntPropertyType(true),new OrmPropertyVisibility(OrmPropertyVisibility::FULL),false),
			'name' => new OrmProperty('name',array('name'),new VarcharPropertyType(null,null,false),new OrmPropertyVisibility(OrmPropertyVisibility::FULL),false),
			'restId' => new OrmProperty('restId',array('rest_id'),new VarcharPropertyType(null,null,false),new OrmPropertyVisibility(OrmPropertyVisibility::FULL),true),
			'blogEntries' => new OrmProperty('blogEntries',array(),new ManyToManyContainerPropertyType(BlogEntryBlogTag::orm(),BlogEntryBlogTag::orm()->getLogicalSchema()->getProperty('BlogEntryTag'),BlogEntryBlogTag::orm()->getLogicalSchema()->getProperty('BlogEntry')),new OrmPropertyVisibility(OrmPropertyVisibility::TRANSPARENT),false)
		);
	}

	/**
	 * @return IOrmProperty
	 */
	function getProperty($name)
	{
		if (!in_array($name, $this->propertyNames)) {
			throw new ArgumentException('name', $name);
		}

		$properties = $this->getProperties();

		return $properties[$name];
	}
}

?>