<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework Generator
 *
 * **********************************************************************************************
 *
 * This is file is autogenerated
 *
 ************************************************************************************************/

/**
 *
 */
final class BlogEntryBlogTagEntityPhysicalSchema implements IPhysicallySchematic
{
	/**
	 * @see IPhysicallySchematic::getDBTableName()
	 * @return string
	 */
	function getDBTableName()
	{
		return 'blog_entry_blog_tag';
	}

	/**
	 * @see IPhysicallySchematic::getDBFields()
	 * @return array
	 */
	function getDBFields()
	{
		return array('___mtm_blog_entry', '___mtm_blog_entry_tag');
	}
}

?>