<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework v.1.0.0
 *
 * **********************************************************************************************
 *
 * This is an auxiliary autogenerated file. Do not edit it as it can be regenerated implicitly!
 *
 ************************************************************************************************/

/**
 * Autogenerated class
 */
final class BlogEntryEntityLogicalSchema implements ILogicallySchematic
{
	private $propertyNames = array('id', 'title', 'text', 'pubTime', 'pubDate', 'restId', 'entryTags');

	/**
	 * Returns the name of the class representing an entity
	 * @return string
	 */
	function getEntityName()
	{
		return 'BlogEntry';
	}

	/**
	 * @return OrmEntity
	 */
	function getNewEntity()
	{
		return new BlogEntry;
	}

	/**
	 * @return OrmProperty|null
	 */
	function getIdentifier()
	{
		return new OrmProperty('id', array('id'), new FundamentalPropertyType(new DBType(DBType::UINT32, false, null, null, null, true)), new OrmPropertyVisibility(OrmPropertyVisibility::FULL), new AssociationMultiplicity(AssociationMultiplicity::ZERO_OR_ONE), false, true);
	}

	/**
	 * Gets the set of {@link OrmProperty}
	 * @return array
	 */
	function getProperties()
	{
		return array(
			'id' => $this->getIdentifier(),
			'title' => new OrmProperty('title', array('title'), new FundamentalPropertyType(new DBType(DBType::VARCHAR, false, null, null, null, false)), new OrmPropertyVisibility(OrmPropertyVisibility::FULL), new AssociationMultiplicity(AssociationMultiplicity::EXACTLY_ONE), false, false),
			'text' => new OrmProperty('text', array('text'), new FundamentalPropertyType(new DBType(DBType::VARCHAR, false, null, null, null, false)), new OrmPropertyVisibility(OrmPropertyVisibility::FULL), new AssociationMultiplicity(AssociationMultiplicity::EXACTLY_ONE), false, false),
			'pubTime' => new OrmProperty('pubTime', array('pub_time'), new BoxablePropertyType('Timestamp', new DBType(DBType::DATETIME, false, null, null, null, false)), new OrmPropertyVisibility(OrmPropertyVisibility::FULL), new AssociationMultiplicity(AssociationMultiplicity::EXACTLY_ONE), false, false),
			'pubDate' => new OrmProperty('pubDate', array('pub_date'), new BoxablePropertyType('Date', new DBType(DBType::DATE, false, null, null, null, false)), new OrmPropertyVisibility(OrmPropertyVisibility::FULL), new AssociationMultiplicity(AssociationMultiplicity::EXACTLY_ONE), false, false),
			'restId' => new OrmProperty('restId', array('rest_id'), new FundamentalPropertyType(new DBType(DBType::VARCHAR, false, null, null, null, false)), new OrmPropertyVisibility(OrmPropertyVisibility::FULL), new AssociationMultiplicity(AssociationMultiplicity::EXACTLY_ONE), false, false),
			'entryTags' => new OrmProperty('entryTags', array(), new ManyToManyContainerPropertyType(BlogEntryBlogTag::orm(), BlogEntryBlogTag::orm()->getLogicalSchema()->getProperty('BlogEntry'), BlogEntryBlogTag::orm()->getLogicalSchema()->getProperty('BlogEntryTag')), new OrmPropertyVisibility(OrmPropertyVisibility::TRANSPARENT), new AssociationMultiplicity(AssociationMultiplicity::ZERO_OR_ONE), false, false)
		);
	}

	/**
	 * @return OrmProperty
	 */
	function getProperty($name)
	{
		if (!in_array($name, $this->propertyNames)) {
			throw new ArgumentException('name', $name);
		}

		$properties = $this->getProperties();

		return $properties[$name];
	}
}

?>