<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework Generator
 *
 * **********************************************************************************************
 *
 * This is file is autogenerated
 *
 ************************************************************************************************/

/**
 *
 */
final class BlogEntryTagEntityPhysicalSchema implements IPhysicallySchematic
{
	/**
	 * @see IPhysicallySchematic::getDBTableName()
	 * @return string
	 */
	function getDBTableName()
	{
		return 'blog_entry_tag';
	}

	/**
	 * @see IPhysicallySchematic::getDBFields()
	 * @return array
	 */
	function getDBFields()
	{
		return array('id', 'name', 'rest_id');
	}
}

?>