<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework Generator
 *
 * **********************************************************************************************
 *
 * This is file is autogenerated
 *
 ************************************************************************************************/

/**
 *
 */
final class BlogEntryBlogTagEntityLogicalSchema implements ILogicallySchematic
{
	private $propertyNames = array('BlogEntry','BlogEntryTag');

	/**
	 * Returns the name of the class representing an entity
	 * @return string
	 */
	function getEntityName()
	{
		return 'BlogEntryBlogTag';
	}

	/**
	 * @return OrmEntity
	 */
	function getNewEntity()
	{
		return new BlogEntryBlogTag;
	}

	/**
	 * @return IOrmProperty|null
	 */
	function getIdentifier()
	{
		return null;
	}

	/**
	 * Gets the set of {@link IOrmProperty}
	 * @return array
	 */
	function getProperties()
	{
		return array(
			'BlogEntry' => new OrmProperty('BlogEntry',array('___mtm_blog_entry'),new AssociationPropertyType(BlogEntry::orm(),new AssociationMultiplicity(AssociationMultiplicity::EXACTLY_ONE),new AssociationBreakAction(AssociationBreakAction::CASCADE)),new OrmPropertyVisibility(OrmPropertyVisibility::FULL),false),
			'BlogEntryTag' => new OrmProperty('BlogEntryTag',array('___mtm_blog_entry_tag'),new AssociationPropertyType(BlogEntryTag::orm(),new AssociationMultiplicity(AssociationMultiplicity::EXACTLY_ONE),new AssociationBreakAction(AssociationBreakAction::CASCADE)),new OrmPropertyVisibility(OrmPropertyVisibility::FULL),false)
		);
	}

	/**
	 * @return IOrmProperty
	 */
	function getProperty($name)
	{
		if (!in_array($name, $this->propertyNames)) {
			throw new ArgumentException('name', $name);
		}

		$properties = $this->getProperties();

		return $properties[$name];
	}
}

?>