<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework Generator
 *
 * **********************************************************************************************
 *
 * This is file is autogenerated
 *
 ************************************************************************************************/

/**
 *
 */
final class ConfigurationEntryEntityLogicalSchema implements ILogicallySchematic
{
	private $propertyNames = array('id','value');

	/**
	 * Returns the name of the class representing an entity
	 * @return string
	 */
	function getEntityName()
	{
		return 'ConfigurationEntry';
	}

	/**
	 * @return OrmEntity
	 */
	function getNewEntity()
	{
		return new ConfigurationEntry;
	}

	/**
	 * @return IOrmProperty|null
	 */
	function getIdentifier()
	{
		return new OrmProperty('id',array('id'),new ObjectPropertyType('ConfigurationKey',null,true),new OrmPropertyVisibility(OrmPropertyVisibility::FULL),false);
	}

	/**
	 * Gets the set of {@link IOrmProperty}
	 * @return array
	 */
	function getProperties()
	{
		return array(
			'id' => new OrmProperty('id',array('id'),new ObjectPropertyType('ConfigurationKey',null,true),new OrmPropertyVisibility(OrmPropertyVisibility::FULL),false),
			'value' => new OrmProperty('value',array('value'),new VarcharPropertyType(null,null,false),new OrmPropertyVisibility(OrmPropertyVisibility::FULL),false)
		);
	}

	/**
	 * @return IOrmProperty
	 */
	function getProperty($name)
	{
		if (!in_array($name, $this->propertyNames)) {
			throw new ArgumentException('name', $name);
		}

		$properties = $this->getProperties();

		return $properties[$name];
	}
}

?>