<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework v.1.0.1
 *
 * **********************************************************************************************
 *
 * This is an auxiliary autogenerated file. Do not edit it as it can be regenerated implicitly!
 *
 ************************************************************************************************/

/**
 * Autogenerated class
 */
final class ConfigurationEntryEntityLogicalSchema implements ILogicallySchematic
{
	private $propertyNames = array('id', 'value');

	/**
	 * Returns the name of the class representing an entity
	 * @return string
	 */
	function getEntityName()
	{
		return 'ConfigurationEntry';
	}

	/**
	 * @return OrmEntity
	 */
	function getNewEntity()
	{
		return new ConfigurationEntry;
	}

	/**
	 * @return OrmProperty|null
	 */
	function getIdentifier()
	{
		return new OrmProperty('id', array('id'), new BoxablePropertyType('ConfigurationKey', new DBType(DBType::VARCHAR, false, null, null, null, false)), new OrmPropertyVisibility(OrmPropertyVisibility::FULL), new AssociationMultiplicity(AssociationMultiplicity::ZERO_OR_ONE), false, true);
	}

	/**
	 * Gets the set of {@link OrmProperty}
	 * @return array
	 */
	function getProperties()
	{
		return array(
			'id' => $this->getIdentifier(),
			'value' => new OrmProperty('value', array('value'), new FundamentalPropertyType(new DBType(DBType::VARCHAR, false, null, null, null, false)), new OrmPropertyVisibility(OrmPropertyVisibility::FULL), new AssociationMultiplicity(AssociationMultiplicity::EXACTLY_ONE), false, false)
		);
	}

	/**
	 * @return OrmProperty
	 */
	function getProperty($name)
	{
		if (!in_array($name, $this->propertyNames)) {
			throw new ArgumentException('name', $name);
		}

		$properties = $this->getProperties();

		return $properties[$name];
	}
}

?>