<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework v.1.0.1
 *
 * **********************************************************************************************
 *
 * This is an auxiliary autogenerated file. Do not edit it as it can be regenerated implicitly!
 *
 ************************************************************************************************/

/**
 * Autogenerated class
 */
final class PhoebiusReleaseEntityLogicalSchema implements ILogicallySchematic
{
	private $propertyNames = array('id', 'date', 'version', 'description', 'link');

	/**
	 * Returns the name of the class representing an entity
	 * @return string
	 */
	function getEntityName()
	{
		return 'PhoebiusRelease';
	}

	/**
	 * @return OrmEntity
	 */
	function getNewEntity()
	{
		return new PhoebiusRelease;
	}

	/**
	 * @return OrmProperty|null
	 */
	function getIdentifier()
	{
		return new OrmProperty('id', array('id'), new FundamentalPropertyType(new DBType(DBType::UINT32, false, null, null, null, true)), new OrmPropertyVisibility(OrmPropertyVisibility::FULL), new AssociationMultiplicity(AssociationMultiplicity::ZERO_OR_ONE), false, true);
	}

	/**
	 * Gets the set of {@link OrmProperty}
	 * @return array
	 */
	function getProperties()
	{
		return array(
			'id' => $this->getIdentifier(),
			'date' => new OrmProperty('date', array('date'), new BoxablePropertyType('Date', new DBType(DBType::DATE, false, null, null, null, false)), new OrmPropertyVisibility(OrmPropertyVisibility::FULL), new AssociationMultiplicity(AssociationMultiplicity::EXACTLY_ONE), false, false),
			'version' => new OrmProperty('version', array('version'), new FundamentalPropertyType(new DBType(DBType::VARCHAR, false, null, null, null, false)), new OrmPropertyVisibility(OrmPropertyVisibility::FULL), new AssociationMultiplicity(AssociationMultiplicity::EXACTLY_ONE), false, false),
			'description' => new OrmProperty('description', array('description'), new FundamentalPropertyType(new DBType(DBType::VARCHAR, false, null, null, null, false)), new OrmPropertyVisibility(OrmPropertyVisibility::FULL), new AssociationMultiplicity(AssociationMultiplicity::EXACTLY_ONE), false, false),
			'link' => new OrmProperty('link', array('link'), new FundamentalPropertyType(new DBType(DBType::VARCHAR, false, null, null, null, false)), new OrmPropertyVisibility(OrmPropertyVisibility::FULL), new AssociationMultiplicity(AssociationMultiplicity::EXACTLY_ONE), false, false)
		);
	}

	/**
	 * @return OrmProperty
	 */
	function getProperty($name)
	{
		if (!in_array($name, $this->propertyNames)) {
			throw new ArgumentException('name', $name);
		}

		$properties = $this->getProperties();

		return $properties[$name];
	}
}

?>