<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework v.1.2.0 Copyright (c) 2010 Scand Ltd.
 *
 * **********************************************************************************************
 *
 * Generated at 2010/05/09 17:22
 *
 * This file is public, and won't be regenerated explicitly. Feel free to modify and extend it.
 *
 ************************************************************************************************/

/**
 * Autogenerated class
 */
final class AnnouncementEntity extends AutoAnnouncementEntity
{
	/**
	 * @return AnnouncementEntity
	 */
	static function getInstance()
	{
		return parent::instance(__CLASS__);
	}
}

?>