<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework Generator
 *
 * **********************************************************************************************
 *
 * This is file is autogenerated
 *
 ************************************************************************************************/

/**
 *
 */
class BlogEntry extends AutoBlogEntry
{
	function toUrl()
	{
		return $this->getPubDate()->toFormattedString('d.m.Y') . '/' . $this->getRestId();
	}
}

?>