<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework v.1.0.0
 *
 * **********************************************************************************************
 *
 * This file is public, and won't be regenerated explicitly.
Feel free to modify and extend it.
 *
 ************************************************************************************************/

/**
 * Autogenerated class
 */
final class BlogEntryTagEntity extends AutoBlogEntryTagEntity
{
	/**
	 * @return BlogEntryTagEntity
	 */
	static function getInstance()
	{
		return parent::instance(__CLASS__);
	}
}

?>