<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework Generator
 *
 * **********************************************************************************************
 *
 * This is file is autogenerated
 *
 ************************************************************************************************/

/**
 *
 */
final class BlogEntryBlogTagEntity extends AutoBlogEntryBlogTagEntity
{
	/**
	 * @return BlogEntryBlogTagEntity
	 */
	static function getInstance()
	{
		return parent::instance(__CLASS__);
	}
}

?>