<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework v.1.0.1
 *
 * **********************************************************************************************
 *
 * This file is public, and won't be regenerated explicitly. Feel free to modify and extend it.
 *
 ************************************************************************************************/

/**
 * Autogenerated class
 */
final class PhoebiusReleaseEntity extends AutoPhoebiusReleaseEntity
{
	/**
	 * @return PhoebiusReleaseEntity
	 */
	static function getInstance()
	{
		return parent::instance(__CLASS__);
	}
}

?>